# Generated by Django 6.1 on 2026-08-20 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appseminario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='jefe',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='pasillo',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='pasillo',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='supermercado',
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre local asignado por el usuario (#cName)', max_length=100)),
                ('phone_number', models.CharField(help_text='Número con código de país (#cNum)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, help_text='Usuario registrado asociado en la plataforma', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts_added', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Nombre del grupo (#gName) en caso de ser chat grupal', max_length=100, null=True)),
                ('is_group', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(help_text='Miembros seleccionados (#gPick)', related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Llamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VO', 'Voz'), ('VI', 'Video')], default='VO', max_length=2)),
                ('estado', models.CharField(choices=[('PE', 'Pendiente'), ('CO', 'Contestada'), ('RE', 'Rechazada'), ('FI', 'Finalizada')], default='PE', max_length=2)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('duracion_segundos', models.IntegerField(default=0)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llamadas_iniciadas', to=settings.AUTH_USER_MODEL)),
                ('invitados', models.ManyToManyField(blank=True, related_name='llamadas_invitadas', to=settings.AUTH_USER_MODEL)),
                ('receptor_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llamadas_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, help_text='Texto o payload cifrado', null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='chat_audio/')),
                ('msg_type', models.CharField(choices=[('text', 'Texto'), ('audio', 'Mensaje de Voz')], default='text', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='appseminario.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('status_text', models.CharField(default='En línea', help_text='Texto corto de estado para #chSub', max_length=100)),
                ('is_online', models.BooleanField(default=False, help_text='Estado del indicador #dot')),
                ('pub_key', models.TextField(blank=True, help_text='Llave pública para cifrado P2P/MQTT', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.DeleteModel(
            name='Jefe',
        ),
        migrations.DeleteModel(
            name='Pasillo',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
        migrations.DeleteModel(
            name='Sucursal',
        ),
        migrations.DeleteModel(
            name='Supermercado',
        ),
    ]
