# Generated by Django 5.2.7 on 2026-08-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appseminario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='visible_in_home',
            field=models.BooleanField(default=True),
        ),
    ]
