# Generated by Django 5.2.7 on 2026-09-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appseminario', '0002_contact_visible_in_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='status_text',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='security_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pub_key',
            field=models.TextField(blank=True, default=''),
        ),
    ]
