# Generated by Django 5.2.7 on 2026-10-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appseminario', '0003_remove_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='public_key',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status_text',
            field=models.CharField(default='En línea', max_length=100),
        ),
    ]
