# Generated by Django 5.2.7 on 2026-10-05 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appseminario', '0004_contact_public_key_userprofile_avatar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('offer', 'Offer'), ('answer', 'Answer'), ('ice', 'ICE')], max_length=10)),
                ('payload', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('llamada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='appseminario.llamada')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
